動画登録機能の作成 完了
misato-okada/mytube pull request #9
Opened 2021-05-17 21:19 UTC by miu-ikeuchi

close #4 

登録機能作成しました、確認よろしくおねがいします！
config.php
functions.php
上記の2つのファイルも変更加えてます。

2021-05-20 15:18 UTC, misato-okada reviewed
少しコメントしました。確認お願いします！

2021-05-20 15:18 UTC, misato-okada commented on new.php
> +                    <input type="text" id="review" name="review" value="<?php echo $review_value; ?>">
<?php echo 〜  の部分は1行なので省略型で書いてもいいかと思います！

あとechoの内容として特殊文字含まれていないですが、調べたところエスケープ漏れを防ぐという意味でh()はつけたほうがいいかもしれないです↓↓
参考URL:https://teratail.com/questions/212107https://teratail.com/questions/212107

2021-05-23 09:33 UTC, misato-okada commented on new.php
> +                    <input type="text" id="review" name="review" value="<? echo h($review_value) ?>">
<? echoは<?=でもっと短くできると思います！

2021-05-23 09:41 UTC, misato-okada commented on new.php
> +                    <input type="text" id="review" name="review" value="<? echo h($review_value) ?>">
```suggestion
                    <input type="text" id="review" name="review" value="<? echo h($review_value) ?>">
```
<? echo のechoも省略して、 <?= の形でかけると思います！

2021-05-23 09:48 UTC, misato-okada requested changes
<? echo のechoも省略して、 <?= の形でかけると思います！

2021-05-23 09:50 UTC, misato-okada reviewed
<? echo のechoも省略して、 <?= の形でかけると思います！

2021-05-23 10:06 UTC, misato-okada commented on new.php
> +                    <input type="text" id="review" name="review" value="<? echo h($review_value) ?>">
え

2021-05-23 10:06 UTC, misato-okada commented on new.php
> +                    <input type="text" id="review" name="review" value="<? echo h($review_value) ?>">
<? echo のechoも省略して、 <?= の形でかけると思います！

2021-05-23 11:49 UTC, misato-okada reviewed
OKです！

2021-05-23 12:05 UTC, kazu-taka requested changes
@miu-ikeuchi 
コメントしたので修正お願いします:bow:

@misato-okada 
私がレビューした内容を参考に、次回レビュー時は同じようなところをチェックするようにお願いします:bow:

2021-05-23 12:05 UTC, kazu-taka commented on functions.php
> +function createNewReview($title, $video_id, $review)
@miu-ikeuchi 
レビューの登録なので、`createReview`だけでもいいのかなと思います✨

2021-05-23 12:05 UTC, kazu-taka commented on functions.php
> +    }
@miu-ikeuchi 
エラー処理いいですね👍

2021-05-23 12:05 UTC, kazu-taka commented on functions.php
> +}
@miu-ikeuchi 
`$err_msg = "<ul class=\"errors\">\n";`と`return $err_msg;`の行について、以下のようにインデントの修正をお願いします:bow:
```php
{
    $err_msg = "<ul class=\"errors\">\n";

    foreach ($errors as $error) {
    $err_msg .= "<li>" . h($error) . "</li>\n";
    }

    $err_msg .= "</ul>\n";

    return $err_msg;
}
```

2021-05-23 12:05 UTC, kazu-taka commented on new.php
> +    $review_value = $_POST['review'];
@miu-ikeuchi 
`$title = filter_input(INPUT_POST, 'title');`と`$title_value = $_POST['title'];`は同じ値を受け取っています。
(video_idとreviewも同じです)
後半の3行は不要なので、filter_inputで受け取ってセットした変数を、htmlのフォーム内にセットするように修正お願いします:bow:

```php
    $title = filter_input(INPUT_POST, 'title');
    $video_id = filter_input(INPUT_POST, 'video_id');
    $review = filter_input(INPUT_POST, 'review');
    $title_value = $_POST['title'];
    $id_value = $_POST['video_id'];
    $review_value = $_POST['review'];
```

2021-05-23 12:05 UTC, kazu-taka commented on new.php
> +
@miu-ikeuchi 
なるべく空行は1行で統一するようにお願いします!!

2021-05-23 12:05 UTC, kazu-taka commented on new.php
> +                    <label for=" video_id">動画ID</label>
@miu-ikeuchi 
細かいですが、`"video_id"`になるように、不要なスペースの削除をおねがいします:bow:

2021-05-23 12:44 UTC, kazu-taka requested changes
@miu-ikeuchi 
修正漏れと私のコメント漏れがあったので再度修正お願いします:bow:

2021-05-23 12:44 UTC, kazu-taka commented on functions.php
> +$err_msg = "<ul class=\"errors\">\n";
@miu-ikeuchi 
こちらのインデントが修正されていないので、修正お願いします！

2021-05-23 12:44 UTC, kazu-taka commented on functions.php
> +    $err_msg .= "<li>" . h($error) . "</li>\n";
@miu-ikeuchi 
foreachの中もインデント修正お願いします！

2021-05-23 12:44 UTC, kazu-taka commented on new.php
> +            </ul>
@miu-ikeuchi 
先程の確認漏れです^^;
`createErrMsg`関数の中でulタグとliタグを生成しているので、ここでのulタグとliタグは不要になります:bow:

2021-05-23 12:58 UTC, kazu-taka requested changes
@miu-ikeuchi 
1点確認お願いします:bow:

2021-05-23 12:58 UTC, kazu-taka commented on new.php
> +            </div>
@miu-ikeuchi 
CSSで`.errors`に対して文字を赤にする等のデザインを適用しています。
今回`div`タグでclassのerrorsを追加していますが、`createErrMsg`関数内の`<ul class=\"errors\">`で、ulタグに対してerrorsを記載しているので、ここでのdivは不要になります！
divを削除して動作確認し、問題ない場合はコミットお願いします:bow:

2021-05-24 00:26 UTC, kazu-taka approved these changes
@miu-ikeuchi 
問題ないのでマージしてOKです！！
![LGTM](https://image.lgtmoon.dev/8222)

2021-05-24 04:22 UTC, merged